### ISSUE TITLE
Investigate GRPC box client

### ISSUE THREAD

**Issue by macpie** [helium/helium-packet-router#82]
The goal here is to only have to support one library for client/server.

**Comment by marcsugiyama** [comment]
# `grpcbox` Review
Nova Labs fork appears to begin with commit `22d7a09bddf968327234f8f8b3413110a212b332` (`v0.13.1`). Since `v0.13.1` in the original version, there appear to be minor improvements to error and timeout handling. These are mostly in client code. Since the fork, Nova Labs appears to have refactored the server stream process into a data structure, refined the server supervisor options, and made some optimizations to initialization. The Nova Labs fork adds `grpcbox_telemetry_stats_handler`. There do not appear to be any changes affecting client code.

`grpcbox` is primarily intended for a micro-services architecture where the services are well defined. As a result, it lacks an API to connect to an "arbitrary" server. All of the endpoints used by clients must be defined in system configuration.

`grpcbox` does not have an asynchonous interface to receiving data.

The remainder of this review is on `grpcbox` client code in the Nova Labs fork.

## Client Example
Proto file Service definitions:
```
rpc GetFeature(Point) returns (Feature) {}
rpc RouteChat(stream RouteNote) returns (stream RouteNote) {}
```
Unary call:

```
Point = #{latitude => 409146138, longitude => -746188906},
{ok, Feature, HeadersAndTrailers} = routeguide_route_guide_client:get_feature(Point).
```

Stream call:
```
{ok, S} = routeguide_route_guide_client:route_chat(),
ok = grpcbox_client:send(S, #{location => #{latitude => 1, longitude => 1}, message => <<"hello there">>}),
{ok, #{message := <<"hello there">>}} = grpcbox_client:recv_data(S)),
```

`grpcbox` users are expected to use the generated functions to make client calls. The client calls do not specify the target server. Users define the client's server in `sys.config`:

```
{client, #{channels => [{default_channel, [{http, "localhost", 8080, []}], #{}}]}}
```
You can also define a specific channel, for example:
```
{client, #{channels => [
    {default_channel, [{http, "localhost", 8080, []}], #{}},
    {test_channel, [{http, "localhost", 18080, []}]}]}}
```
The specific channel can get specified as an option to calls:
```
{ok, Feature, HeadersAndTrailers} = routeguide_route_guide_client:get_feature(Point, #{channel => test_channel}).
```

For stream calls, the caller first allocates a stream for the rpc call, then uses the Stream to send requests and receive responses. There is no asynchronous interface to receive data.

## Setup flow
Connections to client endpoints are created during `grpcbox` initialization:

`grpcbox_app:start`:
- starts `grpcbox_sup`
- calls `grpcbox_channel_sup:start_child` for each channel defined in the system config
  - `grpcbox_channel:init`
    - `gproc_pool:new(ChannelName, BalancerType, [{size, length(Endpoints)}, ..]` for each channel
    - `grpcbox_subchannel:start_link` for each endpoint in the channel

## Unary request

For a unary request, the caller uses the generated client rpc function. This unary call is synchronous and waits for the rpc reply.

`routeguide_route_guide_client:get_feature(Input)`:
- `grpcbox_client:unary`
  - `grpcbox_channel:pick`
    - `gproc:pick_worker` (ets lookup)
  - `grpcbox_client_stream:send_request`
    - `grpc_subchannel:conn`
      - `gen_statem:call`
        - `h2_client:start_link`
    - `h2_connection:new_stream`
      - `h2_stream_set:new_stream`
        - `h2_stream:start_link`
        - `h2_connection:send_body`
          - `h2_stream:set:send_what_we_can`
            - `h2_frame_data:new`
            - `h2_stream:send_data`
              - `sock:send`
                - `gen_tcp:send`
  - `recv_end`
    - `receive`
  - `recv_trailers`
  - `recv_data`
    - `grpcbox_client_stream:recv_msg`
      - `receive`

Response is sent via a `on_receive_data` callback in `grpcbox_client_stream` set with `h2_connection:new_stream`. `grpcbox_client_stream` is the callback module.

```
on_receive_data(Data, State=#{stream_id := StreamId,
                              client_pid := Pid,
                              buffer := Buffer,
                              encoding := Encoding,
                              unmarshal_fun := UnmarshalFun}) ->
    {Remaining, Messages} = grpcbox_frame:split(<<Buffer/binary, Data/binary>>, Encoding),
    [Pid ! {data, StreamId, UnmarshalFun(Message)} || Message <- Messages],
    {ok, State#{buffer => Remaining}};
```

## Stream request/response

Create the stream:

`routeguide_route_guide_client:route_chat`
- `grpcbox_client:stream`
  - `grpcbox_channel:pick`
    - `grpcbox_channel:pick_worker`
    - `grpcbox_client:stream:new_stream`
      - `grpcbox_subchanne:conn`
        - `gen_statem:call`
      - `h2_connection:new_stream`
        - `gen_statem:call`
          - `h2_stream_set:new_stream`
            - `h2_stream:start_link`
      - `h2_connection:send_headers`
        - `gen_statem:cast`
          - `sock:send`
            - `gen_tcp:send`

Send streaming request:

`grpcbox_client:send`
- `grpcbox_client_stream:send_msg`
  - `h2_connection:send_body`
    - `gen_statem:cast`
      - `h2_stream_set:get`
      - `h2_stream_set:queued_data`
      - `h2_stream_set:send_what_we_can`
        - `h2_stream:send_data`
          - `gen_statem:cast`
            - `sock:send`
      - `h2_stream_set:upsert`

Receive streaming response:

`grpcbox_client:recv_data`
- `grpcbox_client_stream:recv_msg`
  - receive data - checks for `'DOWN'` messages and receives trailers; checks for timeout and if the stream process is alive; uses selective receive

Data is delivered via a callback set when creating `h2_stream`.

h2_connection:handle_event({info, {tcp, ...}})
- `sock:recv`
- `gen_statem:cast(self(), {frame, ...})`
- `connected` - state
  - `route_frame`
    - `recv_data`
      - `h2_stream:send_event`
        - `gen_statem:cast`
          - `grpcbox_client:stream:on_receive_data`
            - `! {data, ...}` for each message
            - receive in `grpc_client_stream:recv_msg`

Messages sent on streams traverse two intermediate processes before getting to `gen_tcp`. Messages received from streams also traverse two intermediate processes before getting to the process calling `grpc_client_stream:rcv_data`.

**Comment by marcsugiyama** [comment]
## grpc_client

Local changes:

Branched at 02689e7992ef70b42b6b890db450ae4a7c21a50c (April 6, 2022)

Local changes in helium/grpc_client replaces `http2_client` with helium fork.
Adds `proc_lib` and `http2_client` as `.app` dependencies.

No changes in original version since fork.

Depends on `http2_client`.

`http2_client` local changes:

Branched at 8a6faf3ef1e0f3bb480d52d34ef5181258e99302 (Oct 11, 2017)

Local changes:
1. add connection timeout
2. changes connection's timeout
3. adds monitor of socket
4. catchall for ignoring settings frames

## Flows

### Examples
Proto file definition:

```
rpc RouteChat(stream RouteNote) returns (stream RouteNote) {}
```

Usage:

Create a new stream:

```
{ok, Connection} = grpc_client:connect(tcp, "localhost", 10000),
{ok, Stream} = grpc_client:new_stream(Connection, 'RouteGuide', 'RouteChat', route_guide).
```

Send a request:
```
P1 = #{latitude => 1, longitude => 2},
P2 = #{latitude => 3, longitude => 5},
grpc_client:send(Stream, #{location => P1, message => "something about P1"}),
grpc_client:send(Stream, #{location => P2, message => "something about P2"}).
```

Receive a response:
```
grpc_client:get(Stream).  % polls
grpc_client:rcv(Stream, 1000). % blocks
```

### Connect

`grpc_client:connect`:
- `grpc_client_connection:new`
  - `http2_client:new_connection`
    - `gen_server:start_link`
      - gen_tcp:connect`

`grpc_client:new_stream`:
- `grpc_client_stream:new`
  - gen_server:start_link(grpc_client_stream, ...)`
    - grpc_client_stream:init`
      - grpc_client_connection:new_stream`
        - `http2_client:new_stream`
          - `gen_server:call`

`grpc_client:send`:
- `grpc_client_stream:send`
  - `gen_server:call`
    - `grpc_client_stream:send_msg`
      - `encode`
      - `grpc_client_connection:send_headers`
        - `http2_client:send_headers`
        - `gen_server:call`
          - `http2_client:do_send_headers`
            - `gen_tcp:send`
      - `grpc_client_connection:send_body`
        - `http2_client:send_data`
        - `gen_server:call`
          - `gen_tcp:send`

`grpc_client:get`:
- `grpc_client_stream:get`
  - `gen_server:call`
    - `queue:out`

`grpc_client:rcv`:
- `grpc_client_stream:rcv`
  - `gen_server:call`
    - `queue:out` or `noreply`

Data is queued by grpc_client_stream on receiving `'RECV_DATA'`
- `decode`
- `info_response`
  - `gen_server:reply` or queue data

`http2_client`:
- `handle_info`
  - handle_packet`
    - handle_message0`
      - handle_message`
        - handle_data`
          - `Owner ! 'RECV_DATA'`
  - `active_once`
    - `inet:setopts {active, once}`

Note that there is no back pressure between `http2_client` and `grpc_client_stream`. If `grpc_client:get`/`rcv` is not called, decoded messages accumulate in the `grpc_client_stream` mailbox.

Data sent to the server traverses two processes before calling `gen_tcp:send`. Data from the server also passes through two intermediate processes before it is retrieved by the client application.

**Comment by marcsugiyama** [comment]
From a process architecture point of view, both `grpcbox_client` and `grpc_client` require two process hops to send a request to the server and to retrieve a response from the server. Neither supports an asynchronous interface to reading responses from the server. `grpcbox_client` has mechanisms for connection pooling/load balancing to the server. It does not appear that `grpc_client` supports this.

I think we should settle on `grpcbox_client`. There doesn't appear to be a significant process architecture difference as compared to `grpc_client` and there are some additional advantages:
1. `grpcbox_client` supports records for encoding/decoding messages so we can remove code translating from record to map and map to record.
2. We're using `grpcbox` for the grpc server
3. We can use `grpcbox_client` generated client code/functions
