### ISSUE TITLE
Investigate stream half closed

### ISSUE THREAD

**Issue by macpie** [helium/helium-packet-router#93]

**Comment by Stargazer191** [comment]
Class C device downlink issue:

Problem:
Downlink seems to only happen intermittently. Repeatable scenarios in which downlinks are successful and unsuccessful are:
  
1) If I get the "stream half-closed" after an uplink, It will not take any downlink message (I was able to enqueue and the queued message leave chirpstack but I do not see it reflect on the gateway since it still stuck on "stream half-closed"

2) In order to do a downlink, I manually sent uplink until I do not get the "stream half-close" then I can successfully send a downlink

3) The "stream half-close" message always happen after a downlink but not always on an uplink. It always happen after the second consecutive uplink.
